# Generated by Django 4.1.7 on 2023-03-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_items_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_image',
            field=models.CharField(default='https://www.everestkitchenpa.com/assets/images/menuShortCuts/momoShortCut.jpg', max_length=500),
        ),
    ]
